name: Build Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            os-name: windows
            target: x86_64-pc-windows-msvc
            executable-extension: .exe
          - os: ubuntu-latest
            os-name: linux
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup toolchain install nightly
          rustup component add rust-src --toolchain nightly

      - name: Build
        run: cargo +nightly build -Z build-std=std,panic_abort --target ${{ matrix.target }} --release

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os-name }}-client
          path: ./target/${{ matrix.target }}/release/client${{ matrix.executable-extension }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os-name }}-server
          path: ./target/${{ matrix.target }}/release/server${{ matrix.executable-extension }}
