name: Build Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup toolchain install nightly
          rustup component add rust-src --toolchain nightly

      - name: Build
        run: cargo +nightly build -Z build-std=std,panic_abort --target x86_64-pc-windows-msvc --release

      - uses: actions/upload-artifact@v4
        with:
          name: windows-client
          path: target/release/client.exe

      - uses: actions/upload-artifact@v4
        with:
          name: windows-server
          path: target/release/server.exe

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup toolchain install nightly
          rustup component add rust-src --toolchain nightly

      - name: Build
        run: cargo +nightly build -Z build-std=std,panic_abort --target x86_64-unknown-linux-gnu --release

      - uses: actions/upload-artifact@v4
        with:
          name: linux-client
          path: target/release/client

      - uses: actions/upload-artifact@v4
        with:
          name: linux-server
          path: target/release/server
